### ISSUE TITLE
bug(timer): Click "Start a new Pomodoro" in long break dialog doubles timers

### ISSUE THREAD

**Issue by DavidWiesner** [gfreeau/cinnamon-pomodoro#60] opened 2016-08-28 16:31 UTC
Thanks for the applet!
Pomodoro is great to keep the head on the important tasks. But there is a bug in your applet.
Clicking on "Start a new Pomodoro" in long break dialog will double the timers.  So the long break timer and the new pomodoro timer will both run at the same time. 

Reset timers in the right click menu will only affect the new pomodoro timer. There is no way to stop the old timer. **Even removing the applet from the toolbar doesn't help!!!** It's still plaing sounds after 25 or 5 minutes.

Can you please fix that. There should be no timer hanging around in my system :) especially after I removed the applet from the toolbar

regards,
David

**Comment by gfreeau** [comment] 2016-08-30 11:28
I cannot reproduce this on cinnamon 2.8.8. What version are you using?

Sounds are played externally by SoX Play. If you can reproduce the issue please check your running processes and post what you find.

**Comment by DavidWiesner** [comment] 2016-08-30 12:22
Thanks for the fast answer.
But your script won't help. 

I try to run this but there is no output.   Even when the Pomodoro-Applet is running. The play command is only running in exact this moment, when the sound is playing. 

regards,
David

**Comment by kunnix** [comment] 2016-10-04 02:55
I believe this is fixed by #65

You can test it here: https://github.com/kunnix/cinnamon-pomodoro/tree/patch-fix-timers-inconsistencies

Feel free to close it after #65 is merged.

**Closed** 2016-10-04 12:42 UTC
